# connection properties
connection:
    host: 172.22.0.1 # gateway of pg-container
    db: dv2
    port: 5432
    user: postgres
    pw: postgres
    schemas:
      stage: stage 
      edwh: vault

rv:   # raw vault
  hubs:
    hub_tax_bundle:         # name des hubs
      hk: hk_tax_bundle     # benamung des hashkeys
      bk: tax_bundle_id     # benamung des bks in der zieltabelle
      overwrite: False      # drop & recreate ? (tbd)

      src:                    
        v_report_taxation_bundle:         # quelle
          bk: tax_bundle_id               # name des bk-felds in quelle
          bkeycode: default               # collision-code optional, defaults to 'default'
          tenant: default                 # tenant-id, defaults to 'default'          

        v_report_ziffer:                  # 2te quelle
          bk: tax_bundle_id               # name des bk-felds in quelle     
          

    hub_ziffer:
      hk: hk_ziffer
      bk: ziffer
      overwrite: False

      src:
        v_report_dict_ziffer:
          bk: ziffer
    
  links:
    lnk_taxbundle_ziffer:
      hk: hk_l_taxbundle_ziffer
      overwrite: False

      src:
        v_report_ziffer:
          bkeycode: default
          tenant: default           
          bks:
            - tax_bundle_id
            - ziffer
            
          #cks: # dependent child keys
          #
            
        v_report_taxation_bundle:         
          bks: 
            - tax_bundle_id               
            - ziffer
          bkeycode: default               
          tenant: default   