# connection properties
#
connection:
    host: 172.28.0.1 # gateway of pg-container
    db: dv2
    port: 5432
    user: postgres
    pw: postgres
    schemas:
      stage: stage 
      edwh: vault

hubs:
  hub_tax_bundle:         # name des hubs
    hk: hk_tax_bundle     # benamung des hashkeys
    overwrite: False      # drop & recreate ? (tbd)

    src:                    
      table: v_report_taxation_bundle # quelle
      bk: tax_bundle_id               # name des bk-felds
      type: int                       # typ des bk-felds

  hub_ziffer:
    hk: hk_ziffer
    overwrite: False

    src:
      table: v_report_dict_ziffer
      bk: ziffer
      type: int
  
links:
  l_taxbundle_ziffer:
    hk: hk_l_taxbundle_ziffer
    overwrite: False

    src:
      table: v_report_ziffer
      bks: 
        tax_bundle_id:
          type: int
        ziffer:
          type: int